name: iMOV
options:
  bundleIdPrefix: com.xte1
targets:
  iMOV:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iMOV
    settings:
      INFOPLIST_FILE: iMOV/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.xte1.iMOV
      CODE_SIGN_STYLE: Automatic
